// <auto-generated />
using GoldDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GoldDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822173000_UniqueExternalBusinessCustomerCodePerShop")]
    partial class UniqueExternalBusinessCustomerCodePerShop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is tracked in ApplicationDbContextModelSnapshot.
        }
    }
}
